version: "3"

services:
  nignx:
    build: nginx
    ports:
      - 80:80
  janus-proxy:
    image: saverops/janus-cloud
    command: janus-proxy
    ports:
      - 8288:8288
  janus:
    build: janus-gateway
    ports:
      - 8188:8188
